[ADD] payment autentication infos in cnab payment
Trust-Code/odoo-brasil pull request #705
Opened 2018-12-05 18:23 UTC by marinaGD

2018-12-10 15:25 UTC, danimaribeiro requested changes

2018-12-10 15:25 UTC, danimaribeiro commented on br_payment_cnab/wizard/payment_cnab_import.py
> +                except AttributeError:
Remover esse except, tem algo de errado para precisar fazer isto.

2018-12-10 18:04 UTC, marinaGD commented on br_payment_cnab/wizard/payment_cnab_import.py
> +                except AttributeError:
Feito!

2018-12-11 01:39 UTC, danimaribeiro approved these changes

2018-12-11 02:17 UTC, merged